// Generated by CoffeeScript 1.6.1
(function() {
  var $, Tag;

  $ = jQuery;

  Tag = (function() {

    function Tag(ops) {
      this.data = $.extend({
        title: '',
        start: 0,
        end: 0
      }, ops);
    }

    Tag.prototype.getStart = function() {
      return this.data.start;
    };

    Tag.prototype.setStart = function(value) {
      return this;
    };

    Tag.prototype.getEnd = function() {
      return this.data.end;
    };

    Tag.prototype.setEnd = function(value) {
      return this;
    };

    return Tag;

  })();

  window.Timeline = (function() {

    function Timeline(ops) {
      this.data = $.extend({
        node: 'body',
        duration: 0
      }, ops);
      this.data.node = $(this.data.node);
      this.data.tags = [];
      if ('tags' in ops) {
        this.setTags(ops.tags);
      }
    }

    Timeline.prototype.getNode = function() {
      return this.data.node;
    };

    Timeline.prototype.getDuartion = function() {
      return this.data.duration;
    };

    Timeline.prototype.setDuartion = function(value) {
      return this;
    };

    Timeline.prototype.getTags = function() {
      return this.data.tags;
    };

    Timeline.prototype.setTags = function(tags) {
      var tag, _i, _j, _len, _len1, _ref;
      _ref = this.getTags();
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        tag = _ref[_i];
        this.delTag(tag);
      }
      for (_j = 0, _len1 = tags.length; _j < _len1; _j++) {
        tag = tags[_j];
        this.addTag(tag);
      }
      return this;
    };

    Timeline.prototype.addTag = function(tag) {
      this.getTags().push(new Tag(tag));
      return this;
    };

    Timeline.prototype.delTag = function(tag) {
      var i;
      i = this.getTags().indexOf(tag);
      this.getTags().splice(i, 1);
      return this;
    };

    return Timeline;

  })();

}).call(this);
