// Generated by CoffeeScript 1.6.1
(function() {

  beforeEach(function() {
    return this.addMatchers({
      toBeInstanceOf: function(constructor) {
        return this.actual instanceof constructor;
      }
    });
  });

  describe('Timeline', function() {
    var line, ops;
    ops = {
      node: '#timeline',
      duration: 60 + 25,
      tags: [
        {
          title: 'first',
          start: 25,
          end: 37
        }, {
          title: 'second',
          start: 10,
          end: 20
        }
      ]
    };
    line = new Timeline(ops);
    it('should have jQuery node', function() {
      return expect(line.getNode() instanceof jQuery).toEqual(true);
    });
    return it('should have tags from ops', function() {
      return expect(line.getTags().length).toEqual(ops.tags.length);
    });
  });

}).call(this);
